# adding region column to grouped_df based on below dictionary
import pandas as pd

country_mappings= {
    'GLOBAL': 'GLOBAL',
    'CANADA': 'NAM',
    'MEXICO': 'NAM',
    'U.S.A.': 'NAM',
    'AUSTRIA': 'Europe',
    'BELARUS': 'Europe',
    'BELGIUM' : 'Europe',
    'BOSNIA-HERZEGOVINA' : 'Europe',
    'CROATIA' : 'Europe',
    'CZECH REPUBLIC' : 'Europe',
    'DENMARK' : 'Europe',
    'FINLAND' : 'Europe',
    'FRANCE' : 'Europe',
    'GERMANY' : 'Europe',
    'GREECE' : 'Europe',
    'HUNGARY' : 'Europe',
    'IRELAND' : 'Europe',
    'ITALY' : 'Europe',
    'LITHUANIA' : 'Europe',
    'MACEDONIA' : 'Europe',
    'NETHERLANDS' : 'Europe',
    'NORWAY' : 'Europe',
    'POLAND' : 'Europe',
    'PORTUGAL' : 'Europe',
    'ROMANIA' : 'Europe',
    'SERBIA' : 'Europe',
    'SLOVAKIA' : 'Europe',
    'SPAIN' : 'Europe',
    'SWEDEN' : 'Europe',
    'SWITZERLAND' : 'Europe',
    'UKRAINE' : 'Europe',
    'UNITED KINGDOM' : 'Europe',
    'RUSSIA' : 'Russia',
    'CHINA' : 'China',
    'BAHRAIN' : 'Middle East',
    'JORDAN' : 'Middle East',
    'KUWAIT' : 'Middle East',
    'IRAN' : 'Middle East',
    'IRAQ' : 'Middle East',
    'ISRAEL' : 'Middle East',
    'OMAN' : 'Middle East',
    'QATAR' : 'Middle East',
    'SAUDI ARABIA' : 'Middle East',
    'SYRIA' : 'Middle East',
    'UNITED ARAB EMIRATES' : 'Middle East',
    'YEMEN' : 'Middle East'
}

country_mappings_df = pd.DataFrame(list(country_mappings.items()), columns=['COUNTRY', 'REGION'])
